INSERT INTO address(id, city, street) VALUES (1, 'Skopje', 'Ibe Palikukja');
INSERT INTO address(id, city, street) VALUES (2, 'Skopje', 'Zlatko Shnajder');
INSERT INTO address(id, city, street) VALUES (3, 'Bitola', 'Partizanska');
INSERT INTO address(id, city, street) VALUES (4, 'Prilep', 'Ilindenska');
INSERT INTO address(id, city, street) VALUES (5, 'Ohrid', 'Aminta Treti');
INSERT INTO address(id, city, street) VALUES (6, 'Debar', 'Apostol Guslarot');
INSERT INTO address(id, city, street) VALUES (7, 'Kichevo', 'Teodosij Gologanov');
INSERT INTO address(id, city, street) VALUES (8, 'Zrze', 'France Preshern');
INSERT INTO address(id, city, street) VALUES (9, 'Kadrifakovo', 'Ivan Cankar');
INSERT INTO address(id, city, street) VALUES (10, 'Negotino', 'Socijalisticka Zora');
INSERT INTO address(id, city, street) VALUES (11, 'Resen', 'Vich');
INSERT INTO address(id, city, street) VALUES (12, 'Struga', 'Franklin Ruzvelt');
INSERT INTO address(id, city, street) VALUES (13, 'Veles', 'Nikola Trimpare');
INSERT INTO address(id, city, street) VALUES (14, 'Gevgelija', 'Kole Nedelkovski');
INSERT INTO address(id, city, street) VALUES (15, 'Delcevo', 'Shumadiska');
INSERT INTO address(id, city, street) VALUES (16, 'Probistip', 'Borka Talevski');
INSERT INTO address(id, city, street) VALUES (17, 'Kavadarci', 'Kosturski Heroi');
INSERT INTO address(id, city, street) VALUES (18, 'Stip', 'Kosta Kirkov');
INSERT INTO address(id, city, street) VALUES (19, 'Radovish', 'Kiro Krstevski');
INSERT INTO address(id, city, street) VALUES (20, 'Berovo', 'Debarca');

INSERT INTO contact(id, name, phone_number, surname, address_id) VALUES (1, 'Risto', '+389078658795', 'Ristov', 1);
INSERT INTO contact(id, name, phone_number, surname, address_id) VALUES (2, 'Ivan', '+389072512847', 'Ivanovski', 2);
INSERT INTO contact(id, name, phone_number, surname, address_id) VALUES (3, 'Mirko', '+390071269845', 'Mirkovski', 3);
INSERT INTO contact(id, name, phone_number, surname, address_id) VALUES (4, 'Slavko', '+420987456123', 'Slavkov', 4);
INSERT INTO contact(id, name, phone_number, surname, address_id) VALUES (5, 'Petko', '+389077948751', 'Petkovski', 5);
INSERT INTO contact(id, name, phone_number, surname, address_id) VALUES (6, 'Trajko', '+411070882648', 'Trajkov', 6);
INSERT INTO contact(id, name, phone_number, surname, address_id) VALUES (7, 'Kurto', '+411089159753', 'Trajkov', 7);
INSERT INTO contact(id, name, phone_number, surname, address_id) VALUES (8, 'Murto', '+389078949768', 'Slavkov', 8);
INSERT INTO contact(id, name, phone_number, surname, address_id) VALUES (9, 'Dimche', '+880880228949', 'Jordanovski', 9);
INSERT INTO contact(id, name, phone_number, surname, address_id) VALUES (10, 'Jovche', '+389071256884', 'Jovchev', 10);
INSERT INTO contact(id, name, phone_number, surname, address_id) VALUES (11, 'Nikolche', '+664155584971', 'Stojanov', 11);
INSERT INTO contact(id, name, phone_number, surname, address_id) VALUES (12, 'Petre', '+664121558546', 'Petkovski', 12);
INSERT INTO contact(id, name, phone_number, surname, address_id) VALUES (13, 'Sashe', '+389072661646', 'Sashev', 13);
INSERT INTO contact(id, name, phone_number, surname, address_id) VALUES (14, 'Marija', '+389078778778', 'Angelovska', 14);
INSERT INTO contact(id, name, phone_number, surname, address_id) VALUES (15, 'Ana', '+420988524135', 'Marija', 15);
INSERT INTO contact(id, name, phone_number, surname, address_id) VALUES (16, 'Milka', '+389070280820', 'Stojmenova', 16);
INSERT INTO contact(id, name, phone_number, surname, address_id) VALUES (17, 'Anastasija', '+664112548976', 'Drugomanova', 17);
INSERT INTO contact(id, name, phone_number, surname, address_id) VALUES (18, 'Filomena', '+389070526948', 'Dinu', 18);
INSERT INTO contact(id, name, phone_number, surname, address_id) VALUES (19, 'Antigona', '+390598121594', 'Petralis', 19);
INSERT INTO contact(id, name, phone_number, surname, address_id) VALUES (20, 'Petrunija', '+390594789789', 'Karamazova', 20);